### ISSUE TITLE
new issues 18/1-2022

### ISSUE THREAD

**Issue by SANDQVISTT** [SANDQVISTT/Jonathan-othman-miki-Niklas18-1#2]
- [ ] Behövs kanske en site-map?
 - [x] #3
 - [x]  Kan vi samla all terminologi på en sida?
 - [x]  Är vi nöjda med färgval? Kan vi göra länkar tydligare?
  - [x] Har huvudsidan en tydlig struktur om vilka undersidor som finns?
 - [x] Har alla undersidor navigering tillbaka till huvudsidan?

**Comment by Sydow75** [comment]
klart
