### ISSUE TITLE
new issue Övning 3

### ISSUE THREAD

**Issue by SANDQVISTT** [SANDQVISTT/Jonathan-othman-miki-Niklas18-1#5]
- [ ] Skapa en startsida som hälsar besökaren välkommen
- [x] Dela upp presentationen i flera sidor
- [ ]  En team sida med ert team-namn
- [ ] En sida per person
- [x] Se över språket
- [ ] Enbart svenska
- [ ] Stavfel?
- [ ] Förkortningar?
- [ ]  Stor bokstav och punkt i alla meningar

**Comment by Sydow75** [comment]
klart
